[package]
name = "day6"
version = "0.1.0"
authors = ["rfrazier <rfrazier716@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.5.4"
lazy_static = "1.4.0"
